# Generated by Django 3.0.3 on 2020-08-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dos', models.CharField(max_length=1000)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whynot.Category')),
            ],
        ),
    ]
