# Generated by Django 3.0.3 on 2020-08-10 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feellikeit', '0002_auto_20200810_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feellikeit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feellikeit',
            name='reason',
            field=models.TextField(default="Maybe it's just too boring."),
        ),
        migrations.AlterField(
            model_name='feellikeit',
            name='snap',
            field=models.ImageField(default='/pics/never_mind.png', upload_to='snap'),
        ),
    ]
